DROP TABLE course;

CREATE TABLE course
	(
     code varchar(20) primary key, 
     name varchar(20), 
     credit integer
    );
    
INSERT INTO course
(code, name, credit)
VALUES
('SWE206', 'Introduction to Software Engineering', 3),
('SWE216', 'Requirements Engineering', 3),
('SWE302', 'Game Programming', 3),
('SWE316', 'Software Design and Construction', 3),
('SWE321', 'Formal Methods and Models in Software Engineering', 3),
('SWE326', 'Software Testing', 3),
('SWE363', 'Web Engineering and Development', 3),
('SWE387', 'Software Project Management', 3),
('SWE399', 'Summer Training', 0),
('SWE411', 'Software Engineering Project I', 3),
('SWE412', 'Software Engineering Project II', 2),
('SWE416', 'Software Architecture', 3),
('SWE422', 'Usability Engineering', 3),
('SWE436', 'Object-Oriented Design Patterns', 3),
('SWE439', 'Software Quality Engineering', 3),
('SWE440', 'Information Security Management', 3),
('SWE445', 'Secure Software Development', 3),
('SWE463', 'Mobile Application Development', 3),
('SWE487', 'Software Processes and Process Improvements', 3),
('SWE490', 'Special Topics I', 3),
('SWE491', 'Special Topics II', 3),
('SWE497', 'Undergraduate Research', 3),
('ICS104', 'Introduction to Programming in Python and C', 3),
('ICS108', 'Object-Oriented Programming', 4),
('ICS202', 'Data Structures and Algorithms', 4),
('ICS253', 'Discrete Structures', 3),
('ICS321', 'Database Systems', 3),
('ICS343', 'Fundamentals of Computer Networks', 4),
('ICS344', 'Information Security', 3),
('ICS353', 'Design and Analysis of Algorithms', 3),
('ICS355', 'Theory of Computing', 3),
('ICS381', 'Principles of Artificial Intelligence', 3),
('ICS398', 'Internship', 6),
('ICS399', 'Summer Training', 0),
('ICS410', 'Programming Languages', 3),
('ICS411', 'Senior Project', 3),
('ICS412', 'Compiler Construction Techniques', 3),
('ICS415', 'Computer Graphics', 3),
('ICS424', 'Advanced Database Systems', 3),
('ICS433', 'Operating Systems', 4),
('ICS437', 'Distributed Systems', 3),
('ICS439', 'Cryptography in Quantum Era', 3),
('COE202', 'Digital Logic Design', 3),
('COE203', 'Digital Logic Design Lab', 1),
('COE233', 'Digital Logic & Computer Organization', 3),
('COE241', 'Data and Computer Communications', 3),
('COE292', 'Introduction to Artificial Intelligence', 3),
('COE301', 'Computer Organization', 4),
('COE302', 'Design and Modeling of Digital Systems', 3),
('COE306', 'Introduction to Embedded Systems', 4),
('COE344', 'Computer Networks', 4),
('COE346', 'Computer & Network Security', 3),
('COE353', 'Fundamentals of Computer Communications', 3),
('COE384', 'Fundamentals of Computer Engineering Design', 4),
('COE398', 'Internship', 6),
('COE399', 'Summer Training', 0),
('COE401', 'Modeling and Simulation of Computer and Network Systems', 3),
('COE402', 'Computer System Performance Evaluation', 3),
('COE403', 'Computer Architecture', 3),
('COE404', 'VLSI Design', 3),
('COE405', 'Microprocessor Design', 3),
('COE406', 'Computer Graphics', 3),
('COE407', 'Computer Vision', 3),
('COE408', 'Machine Learning', 3),
('COE409', 'Natural Language Processing', 3),
('COE410', 'Robotics', 3),
('COE411', 'Senior Project', 3),
('EE201', 'Electric Circuits I', 3),
('EE203', 'Electronics I', 3),
('EE204', 'Fundamentals of Electrical Circuits', 2),
('EE207', 'Signals and Systems', 3),
('EE212', 'Electrical Circuits Laboratory', 1),
('EE213', 'Electric Circuits II', 2),
('EE234', 'Electronics and Microcontrollers', 3),
('EE235', 'Electronics and Microcontrollers Lab', 1),
('EE236', 'Electronic Circuits', 3),
('EE237', 'Electronic Circuits Lab', 1),
('EE271', 'Electric Circuits II Lab', 1),
('EE272', 'Analog and Digital Electronics Lab', 1),
('EE303', 'Electronics II', 3),
('EE304', 'Electronics II Lab', 1),
('EE306', 'Electromechanical Devices', 2),
('EE311', 'Fundamentals of EE Design', 3),
('EE312', 'Electrical Systems & Lighting', 3),
('EE315', 'Probabilistic Methods in Electrical Engineering', 3),
('EE340', 'Electromagnetic Waves and Applications', 3),
('EE341', 'Electromagnetics Lab', 1),
('ISE205', 'Engineering Probability and Statistics', 3),
('ISE291', 'Introduction to Data Science', 3),
('ISE303', 'Operations Research I', 3),
('ISE307', 'Engineering Economic Analysis', 3),
('ISE315', 'Engineering Statistics', 3),
('ISE320', 'Quality Control and Industrial Statistics', 3),
('ISE321', 'Optimization Methods', 3),
('ISE324', 'Work and Process Improvements', 2),
('ISE351', 'Cooperative Work', 0),
('ISE391', 'Industrial Engineering Design', 1),
('ISE398', 'Internship', 0),
('ISE399', 'Summer Training', 0),
('ISE402', 'Production Systems and Inventory Control', 3),
('ISE405', 'Stochastic Systems Simulation', 2),
('ISE413', 'Productivity Engineering and Management', 3),
('ISE420', 'Quality Improvement Methods', 3),
('ISE422', 'Facility Layout and Location', 3),
('ISE426', 'Operations Research II', 3),
('ISE429', 'Maintenance Planning and Control', 3),
('ISE430', 'Industrial Engineering in Healthcare Systems', 3),
('ISE440', 'Engineering Project Management', 3),
('ISE443', 'Human Factors Engineering', 2),
('ISE447', 'Decision Making', 3),
('ISE448', 'Sequencing and Scheduling', 3),
('ISE455', 'Applied Models for Optimal Decisions', 3),
('ME201', 'Dynamics', 3),
('ME203', 'Thermodynamics I', 3),
('ME204', 'Thermodynamics II', 3),
('ME205', 'Materials Science', 3),
('ME210', 'Mechanical Engineering Drawing and Graphics', 3),
('ME216', 'Materials Science and Engineering', 3),
('ME217', 'Materials Science - Lab', 1),
('ME218', 'Introduction to ME Design', 3),
('ME307', 'Machine Design I', 3),
('ME308', 'Machine Design II', 3),
('ME309', 'Mechanics of Machines', 3),
('ME311', 'Fluid Mechanics', 3),
('ME315', 'Heat Transfer', 3),
('ME316', 'Thermo-Fluid Lab', 1),
('ME322', 'Manufacturing Processes I', 3),
('ME323', 'Manufacturing Processes I - Lab', 1),
('ME351', 'COOP Training', 0),
('ME399', 'Summer Training', 0),
('ME406', 'Manufacturing and Design', 3),
('ME407', 'Advanced Manufacturing Laboratory', 1),
('ME413', 'System Dynamics and Control', 3),
('ME414', 'Design Project I', 3),
('ME416', 'Design Project II', 3),
('ME422', 'Propulsion Systems', 3),
('ME423', 'Energy Conversion', 3),
('ME425', 'Compressible Fluid Flow', 3),
('ME427', 'TURBOMACHINERY', 3),
('ME430', 'Air Conditioning', 3),
('ME431', 'Refrigeration', 3),
('ME432', 'Internal Combustion Engines', 3),
('ME436', 'Fluid Power Systems', 3),
('ME437', 'Design and Rating of Heat Exchangers', 3),
('ME438', 'Pumping Machinery', 3),
('ME439', 'Solar Energy Conversion', 3),
('ME446', 'Computational Fluid Dynamics and Heat Transfer', 3),
('ME451', 'Design and Analysis of Engineering Experiments', 3),
('ME452', 'Measurements and Lab Project', 1),
('ME458', 'Design of thermo-fluid systems', 3),
('ME460', 'Thermal Desalination Systems', 3),
('ME462', 'Products and Systems Reliability', 3),
('ME466', 'Fundamentals of Heat Treatment', 3),
('ME468', 'Casting and Welding Engineering', 3),
('ME472', 'Corrosion Engineering I', 3),
('ME479', 'Modern Materials', 3),
('ME480', 'Plastics Materials and Processing', 3),
('ME482', 'Mechanical Vibrations', 3),
('ME484', 'Acoustics', 3),
('ME487', 'Mechanics of Materials', 3),
('ME489', 'FEA in Mechanical Engineering Design', 3),
('ME493', 'Special Topics in Materials and Manufacturing', 3),
('MATH 101', 'Calculus I', 4),
('MATH 102', 'Calculus II', 4),
('MATH 105', 'Finite Mathematics', 3),
('MATH 106', 'Applied Calculus', 3),
('MATH 201', 'Calculus III', 4),
('Math 208', 'Introduction to Differential Equations & Linear Algebra', 4),
('MATH 210', 'Introduction to Sets and Structures', 3),
('MATH 225', 'Introduction to Linear Algebra', 3),
('MATH 302', 'Engineering Mathematics', 3),
('MATH 310', 'Logic and Set Theory', 3),
('MATH 315', 'Development of Mathematics', 3),
('MATH 323', 'Modern Algebra I', 3),
('MATH 325', 'Linear Algebra', 3),
('MATH 333', 'Methods of Applied Mathematics I', 3),
('MATH 336', 'Mathematical Models in Biology', 3),
('MATH 341', 'Advanced Calculus I', 3),
('MATH 353', 'Euclidean and Non-Euclidean Geometry', 3),
('MATH 371', 'Introduction to Numerical Computing', 4),
('MATH 399', 'Summer Training', 0),
('Math 423', 'Modern Algebra II', 3),
('MATH 424', 'Applied Algebra', 3),
('MATH 427', 'Number Theory', 3),
('MATH 432', 'Applied Matrix Theory', 3),
('MATH 433', 'Methods of Applied Mathematics II', 3),
('MATH 441', 'Real Analysis', 3),
('MATH 442', 'Complex Analysis', 3),
('MATH 443', 'Topology', 3),
('MATH 444', 'Algebraic Geometry', 3),
('MATH 445', 'Differential Geometry', 3),
('MATH 446', 'Functional Analysis', 3),
('MATH 447', 'Numerical Analysis', 3),
('MATH 448', 'Mathematical Logic', 3),
('MATH 449', 'Mathematical Statistics', 3),
('MATH 450', 'Mathematical Economics', 3),
('MATH 451', 'Mathematical Finance', 3),
('MATH 452', 'Mathematical Biology', 3),
('MATH 453', 'Mathematical Physics', 3),
('MATH 454', 'Mathematical Chemistry', 3),
('MATH 455', 'Mathematical Engineering', 3),
('MATH 456', 'Mathematical Education', 3),
('PHYS101', 'General Physics I', 3),
('PHYS102', 'General Physics II', 3),
('PHYS204', 'General Physics III', 3),
('PHYS205', 'General Physics III LAB', 1),
('PHYS210', 'Methods of Theoretical Physics', 3),
('PHYS213', 'Modern Physics', 3),
('PHYS215', 'Introduction to Astronomy', 3),
('PHYS234', 'The Physics of How Things Work', 3),
('PHYS261', 'Energy', 3),
('PHYS271', 'Introduction to Special Relativity', 3),
('PHYS300', 'Classical Mechanics I', 4),
('PHYS302', 'Classical Mechanics II', 3),
('PHYS305', 'Electricity and Magnetism I', 3),
('PHYS306', 'Electricity and Magnetism II', 3),
('PHYS307', 'Laser Molecular Spectroscopy', 3),
('PHYS308', 'Electronics', 3),
('PHYS309', 'Experimental Physics', 2),
('PHYS310', 'Quantum Mechanics and Applications I', 3),
('PHYS311', 'Optics', 3),
('PHYS315', 'Astrophysics', 3),
('PHYS336', 'Physics of Semiconductor Devices', 3),
('PHYS353', 'Radiation and Health Physics', 3),
('PHYS365', 'Introduction to Medical Physics', 3),
('PHYS373', 'Introduction to Computational Physics', 2),
('PHYS399', 'Summer Training', 0),
('PHYS403', 'Senior Physics Lab', 0),
('PHYS405', 'Physics Project Laboratory', 1),
('PHYS410', 'Quantum Mechanics and Applications II', 3),
('PHYS413', 'Advanced Optics', 3),
('PHYS415', 'Nuclear Physics', 3),
('PHYS421', 'Particle Physics', 3),
('PHYS425', 'Statistical Physics', 3),
('PHYS431', 'Solid State Physics', 3),
('PHYS435', 'Optics and Lasers', 3),
('PHYS441', 'Mathematical Methods in Physics', 3),
('PHYS445', 'Computational Physics', 3),
('PHYS451', 'Astronomy and Astrophysics', 3),
('PHYS455', 'Space Physics', 3),
('PHYS461', 'Biophysics', 3),
('PHYS465', 'Medical Physics', 3),
('PHYS471', 'Nuclear Engineering', 3),
('PHYS475', 'Particle Physics and Astrophysics', 3),
('PHYS481', 'Nuclear Astrophysics', 3),
('PHYS485', 'The Physics of Climate Change', 3),
('PHYS491', 'Independent Study', 0),
('PHYS495', 'Senior Thesis', 0),
('GS 318', 'World Civilizations', 3),
('GS 321', 'Principles of Human Behavior', 3),
('GS 332', 'Principles of Sociology', 3),
('GS 336', 'Work & Society', 3),
('GS 342', 'International Relations', 3),
('GS 355', 'Cultural Anthropology', 3),
('GS 420', 'Personality Psychology', 3),
('GS 424', 'Business Psychology', 3),
('GS 426', 'Social Psychology', 3),
('GS 434', 'Mass Media & Society', 3),
('GS 447', 'Globalization', 3),
('GS 454', 'Anthropology of Travel', 3),
('GS 457', 'Social Networks', 3),
('GS 494', 'Special Topics I', 3),
('GS 495', 'Special Topics II', 3),
('GS 496', 'Special Topics III', 3),
('CHE 201', 'Principles of Chem. Engg. I', 3),
('CHE 202', 'Principles of Chem. Engg. II', 3),
('CHE 204', 'Fluid Mechanics', 3),
('CHE 300', 'Heat Transfer', 3),
('CHE 303', 'Chemical Engineering Thermodynamics', 3),
('CHE 304', 'Mass Transfer', 3),
('CHE 306', 'Separation Processes', 3),
('CHE 309', 'Chemical Engineering Laboratory I', 2),
('CHE 350', 'Begin Cooperative Work', 0),
('CHE 351', 'Cooperative Work', 9),
('CHE 352', 'End Cooperative Work', 0),
('CHE 399', 'Summer Training', 0),
('CHE 401', 'Process Dynamics and Control', 3),
('CHE 402', 'Kinetics and Reactor Design', 3),
('CHE 404', 'Hydrogen Production and Storage', 3),
('CHE 409', 'Chemical Engineering Laboratory II', 2),
('CHE 422', 'Properties of Fluids', 3),
('CHE 425', 'Process Design and Economics', 3),
('CHE 430', 'Rate-Based Separation Processes', 3),
('CHE 431', 'Membrane Processes Technology', 3),
('CHE 432', 'Principles of Heat Exchanger Design', 3),
('CHE 440', 'Catalysis & Catalytic Processes', 3),
('CHE 444', 'Electrochemical Energy Conversion and Storage', 3),
('CHE 445', 'Biochemical Engineering', 3),
('CHE 446', 'Polymer Engineering', 3),
('CHE 447', 'Sustainable Energy Engineering', 3),
('CHE 448', 'Corrosion Engineering', 3),
('CHE 449', 'Environmental Engineering', 3),
('CHE 450', 'Energy Systems Engineering', 3),
('CHE 451', 'Process Safety Engineering', 3),
('CHE 452', 'Chemical Process Modeling and Simulation', 3),
('CHE 453', 'Chemical Engineering Economics', 3),
('CHE 454', 'Chemical Engineering Plant Design', 3),
('CHE 455', 'Chemical Engineering Research', 3),
('ACCT 110', 'Introduction to Financial Accounting', 3),
('ACCT 210', 'Introduction to Managerial Accounting', 3),
('ACCT 300', 'Accounting Information Systems', 3),
('ACCT 301', 'Intermediate Accounting I', 3),
('ACCT 302', 'Intermediate Accounting II', 3),
('ACCT 305', 'Accounting for Governmental and Non-Profit Entities', 3),
('ACCT 307', 'Islamic Financial Jurisprudence', 3),
('ACCT 311', 'Auditing', 3),
('ACCT 314', 'Computer Control and Audit', 3),
('ACCT 398', 'Internship', 0),
('ACCT 403', 'Advanced Accounting', 3),
('ACCT 406', 'Internal Auditing', 3),
('ACCT 407', 'Financial Statement Analysis', 3),
('ACCT 408', 'Zakat and Business Tax Accounting', 3),
('ACCT 409', 'International Business Taxation', 3),
('ACCT 410', 'Cost Accounting', 3),
('ACCT 411', 'Forensic Accounting', 3),
('ACCT 412', 'Management Control Systems', 3),
('ACCT 413', 'Accounting Ethics', 3),
('ACCT 414', 'Tax Planning and Strategy', 3),
('ACCT 415', 'Financial Reporting and Analysis', 3),
('FIN 200', 'Introduction to Finance', 3),
('FIN 250', 'Financial Management', 3),
('FIN 315', 'Corporate Finance', 3),
('FIN 320', 'Investments', 3),
('FIN 398', 'Internship', 0),
('FIN 410', 'International Financial Management', 3),
('FIN 415', 'Management of Financial Institutions', 3),
('FIN 416', 'Entrepreneurial Finance', 3),
('FIN 421', 'Security Analysis and Portfolio Management', 3),
('FIN 422', 'Financial Risk Management', 3),
('FIN 423', 'Fixed Income Analysis', 3),
('FIN 424', 'Investment Valuation', 3),
('FIN 425', 'Financial Modeling', 3),
('FIN 430', 'Risk Management, Conventional and Islamic Insurance', 3),
('FIN 435', 'Real Estate Investment and Finance', 3),
('FIN 440', 'Islamic Finance', 3),
('FIN 441', 'Governance of Islamic Financial Institutions', 3),
('FIN 442', 'Islamic Capital Markets', 3),
('FIN 443', 'Islamic Financial Derivatives', 3),
('FIN 444', 'Islamic Banking and Financial Markets', 3),
('FIN 445', 'Islamic Wealth Management', 3),
('FIN 446', 'Islamic Financial Accounting and Reporting', 3),
('FIN 447', 'Islamic Financial Law', 3),
('FIN 448', 'Islamic Financial Ethics', 3);

SELECT * FROM course